language: php

php:
    - 7.4
    - 8.0

env:
    matrix:
        - COMPOSER_FLAGS="--prefer-lowest"
        - COMPOSER_FLAGS=""

service:
    - redis-server

before_install:
    - mkdir -p ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d
    - bash <(curl -s https://raw.githubusercontent.com/php-cache/cache/master/build/php/7.2/Redis.sh)

before_script:
    - travis_retry composer self-update
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
    - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
